# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_auto_20170413_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='organisation',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(default='None', max_length=30),
        ),
    ]
