# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-13 21:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0006_auto_20170413_2010'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='Users',
        ),
    ]
