# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0008_auto_20170413_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
