# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-14 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0009_auto_20170414_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='organization',
            field=models.CharField(choices=[('', '--Select Organization--'), ('KH', 'Cambodia'), ('EC', 'Ecuador'), ('HN', 'Honduras'), ('KE', 'Kenya'), ('MM', 'Myanmar'), ('PH', 'Philippines'), ('LK', 'Sri Lanka'), ('TZ', 'Tanzania'), ('UG', 'Ugnada'), ('ZM', 'Zambia'), ('VFI', 'VisionFund International'), ('AFR', 'Africa Regional'), ('ASR', 'Asia Regional'), ('LAR', 'Latin America Regional')], default='None', max_length=3),
        ),
    ]
