# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-03 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0012_auto_20170419_2111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='map',
            options={},
        ),
    ]
